{
  "languages": ["id", "en"],
  "min_confidence": 0.6,
  "enable_gpu": false,
  "engine": "paddle",
  "ocr_version": "PP-OCRv5",
  "det_model_dir": null,
  "rec_model_dir": null,
  "cls_model_dir": null,
  "structure_version": null,
  "text_det_limit_side_len": 1080,
  "text_det_limit_type": "max",
  "text_det_unclip_ratio": 1.5,
  "text_det_box_thresh": 0.5,
  "text_det_db_thresh": 0.2,
  "text_rec_score_thresh": 0.5,
  "use_doc_preprocessor": false,
  "use_doc_orientation_classify": false,
  "use_doc_unwarping": false,
  "use_textline_orientation": false,
  "max_image_size": 2048,
  "table_mode": false,
  "handwriting_mode": false,
  "cache_path": "cache.sqlite3",
  "pdf_text": true,
  "threads": 4,
  "batch_timeout": 60.0,
  "request_timeout": 30.0,
  "rate_limit": 4,
  "max_file_size_mb": 20,
  "download_timeout": 10.0,
  "download_chunk_size": 262144,
  "pipeline_debug": false,
  "use_spell_correction": true,
  "enable_metrics": true,
  "downscale_on_oom": true,
  "max_pdf_pages": null
}
