{
  "languages": ["id", "en"],
  "min_confidence": 0.6,
  "enable_gpu": false,
  "engine": "paddle",
  "ocr_version": "PP-OCRv5",
  "det_model_dir": null,
  "rec_model_dir": null,
  "cls_model_dir": null,
  "structure_version": null,
  "max_image_size": 2048,
  "table_mode": false,
  "handwriting_mode": false,
  "cache_path": "cache.sqlite3",
  "pdf_text": true,
  "threads": 4,
  "batch_timeout": 60.0,
  "request_timeout": 30.0,
  "rate_limit": 4,
  "max_file_size_mb": 20,
  "download_timeout": 10.0,
  "download_chunk_size": 262144,
  "pipeline_debug": false,
  "use_spell_correction": true,
  "enable_metrics": true,
  "downscale_on_oom": true,
  "max_pdf_pages": null
}
